name: Deploy Next.js to Ubuntu

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: 'NODE_ENV=production'
          script: |
            cd /var/www/myproject
            git fetch origin main
            git reset --hard origin/main
            npm ci --omit=dev
            npm run build
            sudo systemctl daemon-reload
            sudo systemctl restart myapp